[profile.default]
# auto_detect_solc = true
allow_paths = ["lib"]
libs = ["lib"]
out = "out"
# solc_version = "0.7.6"
src = "src"

remappings = ['@openzeppelin/contracts=lib/openzeppelin-contracts/contracts']

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
